### PR TITLE
Kris branch

### PR DESCRIPTION
**Pull request by textvrbrln**
A "docs" folder with an overview.md and an update for the "README.md"

### CODE REVIEW

**Comment by Lassulus** [comment]
usually you can rebase on master rather than merging it, not really important but thats how people usually do that :)
btw, is this ready to merge or do you want continue working on it?

**Comment by textvrbrln** [comment]
> usually you can rebase on master rather than merging it, not really important but thats how people usually do that :)  

Good to know. This did not work on my first try, but I'll read on the difference and will try again.

> btw, is this ready to merge or do you want continue working on it?  

I think it would be good for the others to read, so they can comment/change stuff.

**Comment by Lassulus** [comment]
for me it looks good, the commit history is a bit unclean. but I can do that locally if you don't care

**Comment by textvrbrln** [comment]
Yes, please go on. I'm still struggling with Git an happy that my current merge workflow works *somehow*.

**Pull request merged**
